name: Terraform AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        env:
          TF_VAR_bucket_name: public-api-ingestion-bucket-deepak
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_bucket_name: public-api-ingestion-bucket-deepak
        run: terraform apply -auto-approve
